# Generated by Django 3.2.5 on 2022-02-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=256)),
                ('Field', models.CharField(max_length=256)),
                ('Headquarters', models.CharField(max_length=256)),
                ('Description', models.CharField(max_length=2000)),
            ],
            options={
                'unique_together': {('Name', 'Field')},
            },
        ),
        migrations.CreateModel(
            name='JobType1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobType2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Subcategory', models.CharField(max_length=256, unique=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atg_app.jobtype1', to_field='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('JobPosition', models.CharField(max_length=256)),
                ('Location', models.CharField(max_length=256)),
                ('WorkType', models.CharField(max_length=2000)),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atg_app.companydetails')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atg_app.states', to_field='State')),
                ('Subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atg_app.jobtype2', to_field='Subcategory')),
            ],
            options={
                'unique_together': {('Company_id', 'JobPosition')},
            },
        ),
    ]
