# Generated by Django 3.2.5 on 2022-02-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Company_id',
            field=models.ForeignKey(db_column='Company_id', on_delete=django.db.models.deletion.CASCADE, to='atg_app.companydetails'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='State',
            field=models.ForeignKey(db_column='State', on_delete=django.db.models.deletion.CASCADE, to='atg_app.states', to_field='State'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Subcategory',
            field=models.ForeignKey(db_column='Subcategory', on_delete=django.db.models.deletion.CASCADE, to='atg_app.jobtype2', to_field='Subcategory'),
        ),
        migrations.AlterField(
            model_name='jobtype2',
            name='Category',
            field=models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.CASCADE, to='atg_app.jobtype1', to_field='Category'),
        ),
    ]
